# Generated by Django 3.2 on 2021-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
        ),
    ]
