# Generated by Django 3.2 on 2021-04-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumers',
            new_name='Costumer',
        ),
    ]
